name: DMinigames
main: me.net.minigames.main.MainClass
version: 0.3.6.1
dev-url: 
description: Minigame Bundle.

commands:
    paintball:
    pb:
    teamdeathmatch:
    tdm:
    dm:
    dminigames:
    tnt:
    tntrun:
    s:
    spleef:
    parkour:
    pk:
    